inherit_from:
  - .rubocop_todo.yml
  - https://relaxed.ruby.style/rubocop.yml

inherit_gem:
  relaxed-rubocop: .rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.3
  Exclude:
    - .git/**/*
    - node_modules/**/*
    - vendor/**/*
    - bin/**/*

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/application.rb'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/**'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/playlist_of_track.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/concerns/errors_handler.rb'